services:
  - type: web
    name: options-trader
    runtime: node
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      npm install --production=false
      npm run build
    startCommand: npx next start -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PYTHON_VERSION
        value: 3.11
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
