services:
  - type: web
    name: options-trader
    runtime: node
    plan: free
    buildCommand: ./build.sh
    startCommand: . venv/bin/activate && npx next start -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PYTHON_VERSION
        value: 3.11
      - key: NODE_ENV
        value: production
      - key: PYTHON_EXECUTABLE
        value: ./venv/bin/python3
    healthCheckPath: /
    autoDeploy: true
