services:
  - type: web
    name: options-trader
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: bash start.sh
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PYTHON_VERSION
        value: 3.12
      - key: NODE_ENV
        value: production
      - key: PYTHON_EXECUTABLE
        value: ./venv/bin/python3
    healthCheckPath: /
    autoDeploy: true
