import type { OptionContract, NewsItem, MarketData, TradeRecommendation } from "./types"

export const mockMarketData: MarketData[] = [
  {
    symbol: "AAPL",
    price: 178.45,
    change: 2.34,
    changePercent: 1.33,
    volume: 52340000,
    high: 179.2,
    low: 176.8,
    open: 177.1,
    previousClose: 176.11,
  },
  {
    symbol: "NVDA",
    price: 495.22,
    change: -3.45,
    changePercent: -0.69,
    volume: 48920000,
    high: 502.1,
    low: 493.5,
    open: 498.67,
    previousClose: 498.67,
  },
  {
    symbol: "TSLA",
    price: 242.84,
    change: 5.67,
    changePercent: 2.39,
    volume: 98450000,
    high: 245.3,
    low: 238.9,
    open: 239.5,
    previousClose: 237.17,
  },
  {
    symbol: "MSFT",
    price: 378.91,
    change: 1.23,
    changePercent: 0.33,
    volume: 23450000,
    high: 380.5,
    low: 377.2,
    open: 378.0,
    previousClose: 377.68,
  },
]

export const mockNews: NewsItem[] = [
  {
    id: "1",
    headline: "Apple announces breakthrough in AI chip technology",
    source: "Bloomberg",
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    sentiment: "bullish",
    sentimentScore: 0.85,
    symbols: ["AAPL"],
    url: "#",
    summary: "Apple unveils new AI processing capabilities that could revolutionize mobile computing.",
  },
  {
    id: "2",
    headline: "NVIDIA faces increased competition in AI chip market",
    source: "Reuters",
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    sentiment: "bearish",
    sentimentScore: -0.62,
    symbols: ["NVDA"],
    url: "#",
    summary: "New competitors entering the AI chip space may impact NVIDIA market share.",
  },
  {
    id: "3",
    headline: "Tesla reports record deliveries in Q4",
    source: "CNBC",
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    sentiment: "bullish",
    sentimentScore: 0.78,
    symbols: ["TSLA"],
    url: "#",
    summary: "Tesla exceeds analyst expectations with strong quarterly delivery numbers.",
  },
  {
    id: "4",
    headline: "Microsoft Azure gains market share in cloud computing",
    source: "TechCrunch",
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    sentiment: "bullish",
    sentimentScore: 0.71,
    symbols: ["MSFT"],
    url: "#",
    summary: "Azure continues to close the gap with AWS in enterprise cloud services.",
  },
]

export const mockOptions: OptionContract[] = [
  {
    id: "1",
    symbol: "AAPL",
    strike: 180,
    expiration: "2024-12-20",
    type: "call",
    action: "buy",
    premium: 4.5,
    bid: 4.45,
    ask: 4.55,
    volume: 12450,
    openInterest: 45230,
    impliedVolatility: 0.28,
    delta: 0.65,
    gamma: 0.045,
    theta: -0.12,
    vega: 0.18,
    breakeven: 184.5,
    maxProfit: Number.POSITIVE_INFINITY,
    maxLoss: 450,
    probability: 0.68,
    recommendation: "strong_buy",
    reasoning:
      "Strong bullish momentum with positive AI chip news. High delta indicates good leverage. IV relatively low for potential expansion.",
    confidence: 0.87,
  },
  {
    id: "2",
    symbol: "NVDA",
    strike: 490,
    expiration: "2024-11-15",
    type: "put",
    action: "buy",
    premium: 6.2,
    bid: 6.15,
    ask: 6.25,
    volume: 8920,
    openInterest: 32100,
    impliedVolatility: 0.35,
    delta: -0.52,
    gamma: 0.038,
    theta: -0.15,
    vega: 0.22,
    breakeven: 483.8,
    maxProfit: 48380,
    maxLoss: 620,
    probability: 0.55,
    recommendation: "buy",
    reasoning:
      "Increased competition concerns creating downside pressure. Good risk/reward ratio with manageable premium.",
    confidence: 0.72,
  },
  {
    id: "3",
    symbol: "TSLA",
    strike: 250,
    expiration: "2024-12-27",
    type: "call",
    action: "buy",
    premium: 8.9,
    bid: 8.85,
    ask: 8.95,
    volume: 15670,
    openInterest: 52340,
    impliedVolatility: 0.42,
    delta: 0.58,
    gamma: 0.032,
    theta: -0.18,
    vega: 0.25,
    breakeven: 258.9,
    maxProfit: Number.POSITIVE_INFINITY,
    maxLoss: 890,
    probability: 0.62,
    recommendation: "buy",
    reasoning: "Record deliveries driving bullish sentiment. Higher IV provides opportunity for volatility play.",
    confidence: 0.79,
  },
  {
    id: "4",
    symbol: "MSFT",
    strike: 375,
    expiration: "2024-11-22",
    type: "put",
    action: "sell",
    premium: 3.8,
    bid: 3.75,
    ask: 3.85,
    volume: 5430,
    openInterest: 18920,
    impliedVolatility: 0.22,
    delta: -0.38,
    gamma: 0.028,
    theta: 0.09,
    vega: -0.15,
    breakeven: 371.2,
    maxProfit: 380,
    maxLoss: 37120,
    probability: 0.71,
    recommendation: "hold",
    reasoning: "Stable cloud growth supports selling puts for premium collection. Low IV limits upside.",
    confidence: 0.65,
  },
]

export const mockRecommendations: TradeRecommendation[] = mockOptions.map((option, index) => ({
  id: option.id,
  option,
  marketData: mockMarketData[index],
  newsContext: mockNews.filter((news) => news.symbols.includes(option.symbol)),
  score: option.confidence * 100,
  riskLevel: option.maxLoss > 700 ? "high" : option.maxLoss > 500 ? "medium" : "low",
  timeframe: new Date(option.expiration).getTime() - Date.now() > 30 * 24 * 60 * 60 * 1000 ? "long" : "short",
  catalysts: ["Earnings Report", "Product Launch", "Market Sentiment"],
}))
