import { Resend } from 'resend'

// Lazy initialization - only create Resend client when needed (at runtime, not build time)
let resendClient: Resend | null = null

export function getResendClient() {
  if (!resendClient) {
    if (!process.env.RESEND_API_KEY) {
      throw new Error('RESEND_API_KEY is not set in environment variables')
    }
    resendClient = new Resend(process.env.RESEND_API_KEY)
  }
  return resendClient
}

// For backwards compatibility - export as 'resend' but as a getter
export const resend = {
  get emails() {
    return getResendClient().emails
  }
}

export const ANALYST_EMAIL_CONFIG = {
  from: 'Monty Analyst <onboarding@resend.dev>', // Resend's test email for development
  to: process.env.ANALYST_EMAIL_RECIPIENT || 'user@example.com',
  replyTo: 'noreply@example.com'
}

export const ADMIN_EMAIL_CONFIG = {
  from: 'Monty Admin <admin@resend.dev>',
  to: process.env.ADMIN_EMAIL_RECIPIENT || process.env.ANALYST_EMAIL_RECIPIENT || 'admin@example.com',
  replyTo: 'noreply@example.com'
}

/**
 * Convert plain text to simple HTML email with styling
 */
function wrapInHTML(text: string, title: string): string {
  // Add colors to bullish/bearish keywords
  let styledText = text
    .replace(/\(bullish\)/gi, '<span style="color: #16a34a; font-weight: bold;">(BULLISH)</span>')
    .replace(/\(bearish\)/gi, '<span style="color: #dc2626; font-weight: bold;">(BEARISH)</span>')
    .replace(/\bbullish\b/gi, '<span style="color: #16a34a; font-weight: bold;">BULLISH</span>')
    .replace(/\bbearish\b/gi, '<span style="color: #dc2626; font-weight: bold;">BEARISH</span>')
    .replace(/✅/g, '<span style="color: #16a34a;">✅</span>')
    .replace(/⚠️/g, '<span style="color: #f59e0b;">⚠️</span>')
    .replace(/🚨/g, '<span style="color: #dc2626;">🚨</span>')

  // Convert line breaks to HTML
  const htmlContent = styledText
    .split('\n')
    .map(line => line.trim() === '' ? '<br>' : `${line}<br>`)
    .join('\n')

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin: 0; padding: 0; background-color: #f8fafc; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;">
  <div style="max-width: 650px; margin: 0 auto; background-color: #ffffff;">
    <!-- Header -->
    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px 20px; text-align: center;">
      <h1 style="margin: 0; font-size: 26px; font-weight: 700;">${title}</h1>
      <p style="margin: 8px 0 0 0; opacity: 0.9; font-size: 13px;">${new Date().toLocaleString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      })}</p>
    </div>

    <!-- Content -->
    <div style="padding: 30px 25px; line-height: 1.7; color: #1e293b; font-size: 14px;">
      <div style="font-family: 'Courier New', Consolas, monospace; white-space: pre-wrap; word-wrap: break-word;">
        ${htmlContent}
      </div>
    </div>

    <!-- Footer -->
    <div style="background: #f1f5f9; padding: 20px; text-align: center; font-size: 13px; color: #64748b; border-top: 1px solid #e2e8f0;">
      <p style="margin: 0;">
        Generated by <strong style="color: #667eea;">Monty</strong> - Your AI Options Analyst
      </p>
    </div>
  </div>
</body>
</html>
  `.trim()
}

/**
 * Send morning brief email
 */
export async function sendMorningBrief(formattedText: string) {
  const resend = getResendClient()
  const { data, error } = await resend.emails.send({
    from: ANALYST_EMAIL_CONFIG.from,
    to: ANALYST_EMAIL_CONFIG.to,
    replyTo: ANALYST_EMAIL_CONFIG.replyTo,
    subject: `📊 Morning Brief - ${new Date().toLocaleDateString()}`,
    html: wrapInHTML(formattedText, '🌅 Morning Brief'),
    text: formattedText, // Fallback for email clients that don't support HTML
  })

  if (error) {
    console.error('Failed to send morning brief:', error)
    throw error
  }

  return data
}

/**
 * Send nightly brief email
 */
export async function sendNightlyBrief(formattedText: string) {
  const resend = getResendClient()
  const { data, error } = await resend.emails.send({
    from: ANALYST_EMAIL_CONFIG.from,
    to: ANALYST_EMAIL_CONFIG.to,
    replyTo: ANALYST_EMAIL_CONFIG.replyTo,
    subject: `🌙 Nightly Brief - Tomorrow's Battle Plan`,
    html: wrapInHTML(formattedText, '🌙 Nightly Brief'),
    text: formattedText,
  })

  if (error) {
    console.error('Failed to send nightly brief:', error)
    throw error
  }

  return data
}

/**
 * Send market open update email
 */
export async function sendMarketOpenUpdate(formattedText: string) {
  const resend = getResendClient()
  const { data, error } = await resend.emails.send({
    from: ANALYST_EMAIL_CONFIG.from,
    to: ANALYST_EMAIL_CONFIG.to,
    replyTo: ANALYST_EMAIL_CONFIG.replyTo,
    subject: `🔔 Market Open Update - ${new Date().toLocaleTimeString()}`,
    html: wrapInHTML(formattedText, '🔔 Market Open Update'),
    text: formattedText,
  })

  if (error) {
    console.error('Failed to send market open update:', error)
    throw error
  }

  return data
}

/**
 * Send weekly analysis email
 */
export async function sendWeeklyAnalysis(formattedText: string) {
  const resend = getResendClient()
  const { data, error } = await resend.emails.send({
    from: ANALYST_EMAIL_CONFIG.from,
    to: ANALYST_EMAIL_CONFIG.to,
    replyTo: ANALYST_EMAIL_CONFIG.replyTo,
    subject: `📈 Weekly Performance Analysis - ${new Date().toLocaleDateString()}`,
    html: wrapInHTML(formattedText, '📈 Weekly Performance Analysis'),
    text: formattedText,
  })

  if (error) {
    console.error('Failed to send weekly analysis:', error)
    throw error
  }

  return data
}

/**
 * Send admin notification for new user signup
 */
export async function sendAdminSignupNotification(userEmail: string, userName?: string | null) {
  const resend = getResendClient()
  const timestamp = new Date().toLocaleString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZone: 'America/New_York',
    timeZoneName: 'short'
  })

  const content = `
New User Signup Alert!

Email: ${userEmail}
Name: ${userName || 'Not provided yet'}
Signup Time: ${timestamp}

The user has completed their onboarding and is now active in the system.
  `.trim()

  const { data, error } = await resend.emails.send({
    from: ADMIN_EMAIL_CONFIG.from,
    to: ADMIN_EMAIL_CONFIG.to,
    replyTo: ADMIN_EMAIL_CONFIG.replyTo,
    subject: `🎉 New User Signup: ${userEmail}`,
    html: wrapInHTML(content, '🎉 New User Signup'),
    text: content,
  })

  if (error) {
    console.error('Failed to send admin signup notification:', error)
    // Don't throw - we don't want to fail the signup flow if the admin email fails
    return null
  }

  return data
}

/**
 * Send daily usage summary to admin
 */
export async function sendDailyUsageSummary(summaryData: {
  date: string
  newSignups: number
  newSignupEmails: string[]
  activeUsers: number
  scansRun: number
  scansRunUniqueUsers: number
  positionsCreated: number
  positionsCreatedUniqueUsers: number
  positionsClosed: number
  totalUsers: number
  totalOpenPositions: number
}) {
  const resend = getResendClient()

  const content = `
Daily Product Usage Summary - ${summaryData.date}

📊 USER METRICS
• New Signups: ${summaryData.newSignups}
${summaryData.newSignupEmails.length > 0 ? `  → ${summaryData.newSignupEmails.join('\n  → ')}` : ''}
• Active Users (24h): ${summaryData.activeUsers}
• Total Users: ${summaryData.totalUsers}

🔍 ACTIVITY METRICS
• Scans Run: ${summaryData.scansRun} (by ${summaryData.scansRunUniqueUsers} users)
• Positions Created: ${summaryData.positionsCreated} (by ${summaryData.positionsCreatedUniqueUsers} users)
• Positions Closed: ${summaryData.positionsClosed}

💼 CURRENT STATE
• Total Open Positions: ${summaryData.totalOpenPositions}

---
Report generated at ${new Date().toLocaleString('en-US', { timeZone: 'America/New_York', timeZoneName: 'short' })}
  `.trim()

  const { data, error } = await resend.emails.send({
    from: ADMIN_EMAIL_CONFIG.from,
    to: ADMIN_EMAIL_CONFIG.to,
    replyTo: ADMIN_EMAIL_CONFIG.replyTo,
    subject: `📊 Daily Usage Summary - ${summaryData.date}`,
    html: wrapInHTML(content, '📊 Daily Usage Summary'),
    text: content,
  })

  if (error) {
    console.error('Failed to send daily usage summary:', error)
    throw error
  }

  return data
}
