watchlists:
  default:
    - AAPL
    - MSFT
    - NVDA
    - TSLA
    - SPY
    - QQQ
    - IWM
    - AMD
    - COIN
    - HOOD
  growth:
    - SHOP
    - SNOW
    - PLTR
    - CRWD
    - MDB
  high_volatility:
    - HOOD
    - COIN
    - PLTR
    - SMCI
    - AI
    - MARA
  ai_infrastructure:
    - NVDA
    - SMCI
    - AVGO
    - ASML
    - PLTR
    - ANET
  value:
    - KO
    - PG
    - JNJ
    - MCD
    - PEP
    - HD
  small_caps:
    - IWM
    - PLUG
    - RUN
    - FVRR
    - ROKU
    - UPST
  short_squeeze:
    - GME
    - AMC
    - BYND
    - BBBYQ
    - APRN
scanner:
  limit_per_symbol: 3
  batch_size: null  # Scan all symbols every time for comprehensive coverage
  rotation_mode: round_robin
fetcher:
  max_priority_symbols: null
scoring:
  enabled:
    - volume
    - iv_rank
    - liquidity
    - risk_reward
    - event_catalyst
  weights:
    volume: 1.0
    iv_rank: 1.2
    liquidity: 0.8
    risk_reward: 1.5
    event_catalyst: 1.0
  score_bounds:
    min: 0.0
    max: 100.0
adapter:
  provider: yfinance
  settings:
    timeout: 30
cache:
  ttl_seconds: 900
storage:
  backend: sqlite
  sqlite:
    path: data/dev-options.db
    pragmas:
      journal_mode: WAL
      synchronous: NORMAL
