/**
 * Test script to send yourself a Morning Brief email
 *
 * Usage:
 * 1. Add RESEND_API_KEY to .env.local
 * 2. Update YOUR_EMAIL below
 * 3. Run: npx tsx scripts/test-morning-brief-email.ts
 */

import { Resend } from 'resend'

const YOUR_EMAIL = 'your-email@example.com' // ← CHANGE THIS!

async function testEmail() {
  // Check for API key
  if (!process.env.RESEND_API_KEY) {
    console.error('❌ RESEND_API_KEY not found in environment')
    console.error('Add it to .env.local:')
    console.error('RESEND_API_KEY=re_your_key_here')
    process.exit(1)
  }

  console.log('🌅 Fetching morning brief data...')

  // Fetch real morning brief
  const response = await fetch('http://localhost:3000/api/analyst/morning-brief')
  const data = await response.json()

  if (!data.success) {
    console.error('❌ Failed to fetch morning brief:', data)
    process.exit(1)
  }

  console.log(`✅ Brief generated with ${Object.keys(data.brief.uoa_signals).length} UOA signals`)

  // Initialize Resend
  const resend = new Resend(process.env.RESEND_API_KEY)

  // Format email data
  const briefData = data.brief

  // Simple text email (we'll build HTML version later)
  const emailText = `
🌅 MORNING BRIEF
Generated: ${new Date(briefData.timestamp).toLocaleString()}

============================================================

📊 MARKET CONDITIONS

${Object.entries(briefData.market_conditions).map(([symbol, data]: [string, any]) =>
  `${symbol}: $${data.price.toFixed(2)} (${data.trend})`
).join('\n')}

============================================================

🔥 UNUSUAL OPTIONS ACTIVITY (${Object.keys(briefData.uoa_signals).length} stocks)

${Object.entries(briefData.uoa_signals).slice(0, 5).map(([symbol, signal]: [string, any]) => {
  const topCall = signal.call_signals?.[0]
  const topPut = signal.put_signals?.[0]

  let text = `\n${symbol} (${signal.bias.toUpperCase()})\n`
  text += `  Current: $${signal.current_price.toFixed(2)}\n`
  text += `  Volume: ${signal.total_unusual_volume.toLocaleString()}\n`

  if (topCall) {
    text += `  🔥 Call: $${topCall.strike} - ${topCall.vol_oi_ratio.toFixed(1)}x vol/OI ${topCall.is_atm ? '[ATM]' : ''}\n`
  }
  if (topPut) {
    text += `  📉 Put: $${topPut.strike} - ${topPut.vol_oi_ratio.toFixed(1)}x vol/OI ${topPut.is_atm ? '[ATM]' : ''}\n`
  }

  return text
}).join('\n')}

============================================================

🎯 TODAY'S WATCHLIST (${briefData.watchlist.length} stocks)

${briefData.watchlist.slice(0, 10).join(', ')}

============================================================

⏰ Next Update: Market Open (9:35 AM ET)

--
Generated by Monty - Your AI Options Analyst
  `.trim()

  console.log('\n📧 Sending test email...')

  try {
    const { data: emailData, error } = await resend.emails.send({
      from: 'Monty <onboarding@resend.dev>', // Will use this until you verify your domain
      to: [YOUR_EMAIL],
      subject: `🌅 Morning Brief - ${new Date().toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' })}`,
      text: emailText,
    })

    if (error) {
      console.error('❌ Error sending email:', error)
      process.exit(1)
    }

    console.log('\n✅ Email sent successfully!')
    console.log('📬 Email ID:', emailData?.id)
    console.log('\n💡 Check your inbox for the Morning Brief!')
    console.log('📝 Note: Email is from onboarding@resend.dev (until you add your domain)')
  } catch (error) {
    console.error('❌ Failed to send email:', error)
    process.exit(1)
  }
}

// Run the test
testEmail().catch(console.error)
