-- Add exit_friendly_message column to positions table
-- This stores a conversational, user-friendly explanation of the exit signal

ALTER TABLE positions
ADD COLUMN exit_friendly_message TEXT;

-- Add comment to document the column
COMMENT ON COLUMN positions.exit_friendly_message IS 'User-friendly, conversational explanation of the exit signal generated by Monty';
